<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Welcome</strong> use Yii2-cms<br> to create your own enterprise site.' => '<strong>欢迎</strong> 使用 Yii2-cms<br> 来创建您自己的企业网站。',
    'This wizard will install and configure your own platform instance.<br><br>To continue, click Next.' => '该向导将安装和配置你自己的企业网站实例。<br><br>点击下一步继续。',
];
