<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Congratulations</strong>. You\'re done.' => '<strong>祝贺你</strong>， 安装完成。',
    'The installation completed successfully! Have fun with your new platform.' => '新平台安装成功完成！祝你使用愉快。',
    'View frontend' => '浏览网站前台',
    'Go to admin panel' => '去管理后台'
];
