#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

//Dynamic config file is created by application.
$dynamic_config = __DIR__ . '/core/config/dynamic.php';

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/core/config/common.php'),
    require(__DIR__ . '/core/config/console.php'),
    (is_readable($dynamic_config)) ? require($dynamic_config) : []
);

$application = new \core\components\console\Application($config);

$exitCode = $application->run();
exit($exitCode);
