<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Layout Options' => '布局选项',
    'Fixed layout' => '固定布局',
    'Activate the fixed layout. You can\'t use fixed and boxed layouts together' => '激活固定布局。固定布局不能和盒装布局一起使用',
    'Boxed Layout' => '盒装布局',
    'Activate the boxed layout' => '激活盒装布局',
    'Toggle Sidebar' => '展示隐藏左侧菜单',
    'Toggle the left sidebar\'s state (open or collapse)' => '切换左测菜单状态(隐藏或展示)',
    'Sidebar Expand on Hover' => '鼠标停留左侧菜单展开',
    'Let the sidebar mini expand on hover' => '当鼠标停留在小左侧菜单时，菜单展开',
    'Toggle Right Sidebar Slide' => '展示隐藏右侧菜单',
    'Toggle between slide over content and push content effects' => '切换右侧菜单的显示状态',
    'Toggle Right Sidebar Skin' => '切换右侧菜单的皮肤',
    'Toggle between dark and light skins for the right sidebar' => '切换右侧菜单的颜色(暗或亮)',
    'Skins' => '主题颜色',
    'Blue' => '蓝色',
    'Black' => '黑色',
    'Purple' => '紫色',
    'Green' => '绿色',
    'Red' => '红色',
    'Yellow' => '黄色',
    'Blue Light' => '浅蓝',
    'Black Light' => '浅黑',
    'Purple Light' => '浅紫',
    'Green Light' => '浅绿',
    'Red Light' => '浅红',
    'Yellow Light' => '浅黄',
);