<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Language' => '语言',
    'Are you sure you want to delete this item?' => '确定删除此项？',
    'Yes' => '是',
    'No' => '否',
    'Save' => '保 存',
    'Search' => '搜 索',
    'Created At' => '创建时间',
    'Created By' => '创建人',
    'Updated At' => '修改时间',
    'Updated By' => '修改人',
    'Update' => '修 改',
    'Delete' => '删 除',
    'Back to list' => '返回列表',
    'Create' => '创 建',
    'Status' => '状 态',
    'Name' => '名 称',
    'Parent ID' => '父 类',
    'Sort Order' => '排 序',
    'Thumb' => '图 片',
    'Please Filter' => '请选择',
    'View' => '查 看',
    'Operation' => '操 作',
    'File Setting' => '附件设置',
    'Enabled' => '显 示',
    'Disabled' => '隐 藏',
    'Back To List' => '返回列表',
    'Update successfully' => '修改成功',
    'Ok' => '确定',
    'Cancel' => '取消',
    'Please check some item' => '请选择一些项',
    'Export' => '导出',
];
