<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Company Info' => '公司信息管理',
    'Basic Setting' => '基础设置',
    'Banner Management' => '轮播管理',
    'Partner Management' => '客户管理',
    'Link Management' => '频道管理',
    'Contact Management' => '留言管理',
    'Create Banner' => '创建轮播图',
    'Update Banner: ' => '修改轮播图：',
    'Partners' => '客户管理',
    'Create Partner' => '添加客户',
    'Update Partner: ' => '修改客户：',
    'Create Link' => '创建频道',
    'Links' => '频道管理',
    'Update Link: ' => '修改频道',
    'Contacts' => '留言管理',
    'Read' => '已 读',
    'Unread' => '未 读',
    'Services Management' => '服务管理',
    'Services' => '服务管理',
    'Open All' => '展开所有',
    'Create Service' => '创建服务',
    'Close All' => '折叠所有',
];
