<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Products Management' => '案例管理',
    'Category Management' => '案例分类管理',
    'Industry Management' => '行业管理',
    'Products' => '案例管理',
    'Categories' => '分类管理',
    'Open All' => '展开所有',
    'Create Category' => '创建分类',
    'Update Category: ' => '修改分类：',
    'Create Products' => '创建案例',
    'Industry Categories' => '行业管理',
    'Update Products: ' => '修改案例：',
    'Album Images' => '相 册',
    'Close All' => '折叠所有',
];
